name: deeplearning
channels:
  - pytorch
dependencies:
  - python=3.7.5
  - numpy
  - matplotlib
  - pytorch
  - torchvision
  - pyyaml
  - tensorboard
  - coloredlogs
  - pip
  - pip:
    - torchsummary
