learning_rate: 0.001
weight_decay: 0.00001 # ADAM decay
color_channels: 3
supervised_ratio: 0.1
batch_size: 1000

# must be configured in env.yml 
dataset: cifar10 # Supports mnist|cifar10
  sub: asdf
decoding_criterion: MSELoss # Supports: MSELoss
prediction_criterion: CrossEntropyLoss # Supports: CrossEntropyLoss

# pretraining_store must be a path !
# pretraining_load must be a file name !
layers:
  - num_epoch: 1
    optimizer: Adam
    pretraining_load: trained_models/cifar10/layer_0_stack.pickle
    pretraining_store: null
    # pretraining_store: trained_models/cifar10 
    # pretraining_load: null 
    upstream: RandomMapping

  - num_epoch: 10
    optimizer: Adam
    pretraining_store: null
    pretraining_load:  null
    upstream: None
    