learning_rate: 0.01
weight_decay: 0.00001 # ADAM decay
color_channels: 3
supervised_ratio: 0.1
batch_size: 1000

# must be configured in env.yml 
dataset: cifar10 # Supports mnist|cifar10
decoding_criterion: MSELoss # Supports: MSELoss
prediction_criterion: CrossEntropyLoss # Supports: CrossEntropyLoss

# pretraining_store must be a path !
# pretraining_load must be a file name !
layers:
  - num_epoch: 1
    optimizer: Adam
    #pretraining_load: trained_models/cifar10/layer_0_stack.pickle
    #pretraining_store: null
    pretraining_load: null 
    pretraining_store: trained_models/cifar10 

    # Supports RandomMap | ConvMap | DecoderMap
    upstream: DecoderMap
    upstream_params:
      in_shape: !!python/tuple [24,16,16]
      out_shape: !!python/tuple [3,32,32]

  - num_epoch: 1
    optimizer: Adam
    pretraining_store: null
    pretraining_load:  null
    upstream: None
    