ae_loss_function: (us+s)*(1-a)+p*a+r
augmentation: true
batch_size: 128
color_channels: 3
dataset: cifar10
dataset_transform: heavy_20
decoding_criterion: MSELoss
layers:
- dropout_rate: 0.6
  encoder_type: A
  kernel_size: 3
  learning_rate: 0.001
  model: VGGn
  num_epoch: 50
  optimizer: Adam
  pretraining_load: null
  pretraining_store: false
  upstream_params: null
- dropout_rate: 0.6
  encoder_type: A
  kernel_size: 3
  learning_rate: 0.001
  model: VGGn
  num_epoch: 50
  optimizer: Adam
  pretraining_load: null
  pretraining_store: false
  upstream_params: null
- dropout_rate: 0.6
  encoder_type: B
  kernel_size: 3
  learning_rate: 0.001
  model: VGGn
  num_epoch: 50
  optimizer: Adam
  pretraining_load: null
  pretraining_store: false
  upstream_params: null
- dropout_rate: 0.6
  encoder_type: B
  kernel_size: 3
  learning_rate: 0.001
  model: VGGn
  num_epoch: 50
  optimizer: Adam
  pretraining_load: null
  pretraining_store: false
  upstream_params: null
- dropout_rate: 0.65
  encoder_type: C
  kernel_size: 3
  learning_rate: 0.001
  model: VGGn
  num_epoch: 50
  optimizer: Adam
  pretraining_load: null
  pretraining_store: false
  upstream_params: null
- dropout_rate: 0.65
  encoder_type: C
  kernel_size: 3
  learning_rate: 0.001
  model: VGGn
  num_epoch: 50
  optimizer: Adam
  pretraining_load: null
  pretraining_store: false
  upstream_params: null
- dropout_rate: 0.65
  encoder_type: C
  kernel_size: 3
  learning_rate: 0.001
  model: VGGn
  num_epoch: 50
  optimizer: Adam
  pretraining_load: null
  pretraining_store: false
  upstream_params: null
- dropout_rate: 0.65
  encoder_type: C
  kernel_size: 3
  learning_rate: 0.001
  model: VGGn
  num_epoch: 50
  optimizer: Adam
  pretraining_load: null
  pretraining_store: false
  upstream_params: null
- dropout_rate: 0.5
  learning_rate: 0.001
  model: VGGlinear
  num_epoch: 50
  optimizer: Adam
  pretraining_load: null
  pretraining_store: false
  upstream_params: null
model_path: trained_models/ex1_w=50
pred_loss_weight: 0.9
prediction_criterion: CrossEntropyLoss
supervised_ratio: 0.2
test_every_n_epochs: 1
train_mode: wave
vgg_dropout: 0.5
vgg_version: A
waves: 50
weight_decay: 0.0
